### ISSUE TITLE
编译问题--预编译的libwebrtc.a和头文件版本错误或缺失

### ISSUE THREAD

**Issue by flying0712** [MemeTao/webrtc-native-samples#2]
非常感谢MemeTao提供的简洁易读、功能针对性强的源码和配套文档，非常适合webrtc native的入门到深入学习。也非常期待作者接下来的更新~~

作者对工程的构建说明已非常清晰，然而本人经验尚浅，在实践该工程中有遇到**编译问题**，折腾一番后初步解决，现记录下遇到的问题和解决方法，希望像我一样的初学者后来者能免掉这番经历。

**问题描述**：该工程的子工程为libwebrtc头文件，但未提供配套的libwebrtc.a，需自己编译webrtc源码或获取libwebrtc.a，并且需要注意的是若仅添加了libwebrtc.a 而没有替换配套的libwebrtc头文件，会编译错误。
**解决办法**：从这里获取libwebrtc.a和头文件：https://github.com/shiguredo-webrtc-build/webrtc-build/releases
包含include和lib，然后按webrtc-native-samples中webrtc头文件目录组织；同时，链接时指定获取的libwebrtc.a。我试m87.4280.10.0和m87.4280.0.0的，都可以。
优化：可以用CMake维护工程，也方便IDE调试。我这里粗略写了个，可以参考https://github.com/flying0712/webrtc-native-samples/blob/master/CMakeLists.txt （原工程audio-channle应该是拼写笔误，已改为audio-channel）

再次感谢作者，期待作者的更新~

**Comment by MemeTao** [comment]
你可以直接将你的修改提交上来么?  谢谢啦!

**Comment by flying0712** [comment]
非常乐意~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MemeTao/webrtc-native-examples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月23日(星期二) 下午2:17
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [MemeTao/webrtc-native-examples] 编译问题--预编译的libwebrtc.a和头文件版本错误或缺失 (#2)





 
你可以直接将你的修改提交上来么?  谢谢啦!
